---

- hosts: all
  become: true
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:

  - name: install apache and php package
    package:
      name:
        - apache2
        # - "{{ apache_package }}"
        - libapache2-mod-php
        # - "{{ php_package }}"
      state: latest
      update_cache: yes

