---

- hosts: all
  become: true
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  pre_tasks:

  - name: install update (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install update (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php package
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        # - "{{ apache_package }}"
        - libapache2-mod-php
        # - "{{ php_package }}"
      state: latest

- hosts: db_servers
  become: true
  tasks:
  
  - name: Install mariadb package
    tags: ubuntu,db,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
  
  - name: Install mariadb package
    tags: samba
    apt:
      name: samba
      state: latest
    when: ansible_distribution == "Ubuntu"
